[WIP] Initial pass at integrating CMARK credit retirements into RA
KlimaDAO/klimadao-solidity pull request #74
Opened 2024-12-12 02:56 UTC by 0xAurelius

Still need to confirm some details and add the Facet

2025-01-07 21:59 UTC, psparacino requested changes

2025-01-07 21:59 UTC, psparacino commented on src/infinity/facets/Bridges/CMARK/RetireCMARKFacet.sol
> +    function cmarkRetireExactCarbonWithEntity(
Is `cmarkRetireExactCarbonWithEntity` needed here? The entity is only assigned conditionally if empty above, so `cmarkRetireExactCarbonWithEntity` shouldn't be necessary if only options are empty string (which becomes "KlimaDAO Retirement Aggregator") and a valid entity string

2025-01-07 21:59 UTC, psparacino commented on src/infinity/libraries/Bridges/LibCMARKCarbon.sol
> +     * @notice                     Retire a CMARK project token
`poolToken` param missing from natspec. if poolToken will never be needed though for `retireCmark` it might be clearer to remove it from the params altogether and just pass address(0) to the `saveRetirementDetails` poolToken arg.

2025-01-07 21:59 UTC, psparacino commented on src/infinity/libraries/LibRetire.sol
> +        CMARK
Just a note to update the subgraphs before doing a production retirement, otherwise they will break from the unknown registry not found in the enum.

This PR: https://github.com/KlimaDAO/klima-subgraph/pull/178 would fix that error. However I've held off on merging this as I wanted to investigate whether the `unsupported_registry` would actually bubble up and break the api.

2025-01-07 21:59 UTC, psparacino commented on test/infinity/Bridge/CMARK.RetireCMARK.t.sol
> +        uint256 tokenId = 1; // TODO: decide how to set this
tokenId should just be `0` if the cmark contract represents a credit vs a project. i don't see the cmark contracts using tokenIds anywhere?

2025-01-07 21:59 UTC, psparacino commented on test/infinity/Bridge/CMARK.RetireCMARK.t.sol
> +        uint256 retireAmount = 100e18;
could fuzz here instead. I don't think it's essential in this case but it's a good sanity check.

2025-01-08 15:55 UTC, 0xAurelius commented on src/infinity/libraries/LibRetire.sol
> +        CMARK
did that here in a standalone PR: https://github.com/KlimaDAO/klima-subgraph/pull/329

2025-01-08 15:55 UTC, 0xAurelius commented on test/infinity/Bridge/CMARK.RetireCMARK.t.sol
> +        uint256 retireAmount = 100e18;
do we have any examples elsewhere in the repo of doing fuzzing?

2025-01-08 15:58 UTC, psparacino commented on test/infinity/Bridge/CMARK.RetireCMARK.t.sol
> +        uint256 retireAmount = 100e18;
hm, guess not. i guess we are doing that routinely only in the marketplace repo.

2025-01-08 16:02 UTC, psparacino commented on src/infinity/libraries/Bridges/LibCMARKCarbon.sol
> +    event CarbonRetired(
the CarbonRetired event signature, at least in the subgraph, still requires a pool param, so can be address(0) here. tokenId can be omitted though

```yaml
      eventHandlers:
        - event: CarbonRetired(uint8,indexed address,string,indexed address,string,string,indexed address,address,uint256)
          handler: handleCarbonRetired
        - event: CarbonRetired(uint8,indexed address,string,indexed address,string,string,indexed address,address,uint256,uint256)
          handler: handleCarbonRetiredWithTokenId
          ```

2025-01-08 16:05 UTC, psparacino commented on src/infinity/libraries/LibRetire.sol
> +                address(0), // Direct retirement, no pool token
is there a reason to keep the address(0) for the poolToken param? Maybe there is for clarity(?). If it will always be irrelevant for cmark credits we can just take that param out of that function altogether.

2025-01-08 16:05 UTC, psparacino approved these changes

2025-01-08 16:45 UTC, 0xAurelius commented on src/infinity/libraries/LibRetire.sol
> +                address(0), // Direct retirement, no pool token
ah yeah good catch I forgot to remove this here

2025-01-08 16:45 UTC, 0xAurelius commented on src/infinity/libraries/Bridges/LibCMARKCarbon.sol
> +    event CarbonRetired(
yep good catch, added it back into the event

2025-01-16 20:53 UTC, 0xAurelius commented
Plan is to run through a local test of the upgrade for this change, meeting with @Atmosfearful next week to go over that

2025-02-06 23:27 UTC, Atmosfearful approved these changes

2025-02-06 23:27 UTC, Atmosfearful commented on src/infinity/facets/Bridges/CMARK/RetireCMARKFacet.sol
> +        return LibRetire.getTotalRetirements(details.beneficiaryAddress);
Just curious, how does this value actually get incremented? Is it a side effect of `retireCMARK() -> saveRetirementDetails()` ?

2025-02-20 17:13 UTC, merged